version: '3.8'
services:
  frontend:
    build:
      context: ./frontend
    container_name: vue-project
    volumes:
      - ./frontend/vue-project:/src
    stdin_open: true
    tty: true
    command: yarn serve --port 3000

  nginx:
    restart: always
    build:
      context: ./nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
